"""
scripts/aggregate_section_5_5.py
================================
Builds tab_continual_retention.tex for Ch5 §5.5 (Retention and continual learning).

Reports per-bench eval-fold EM at C0 and C5 (the start and end of the trajectory)
and the cycle-to-cycle EM stability range. The full retention probe panel is
already reported in tab_pooled_trajectory (§5.2); this table focuses on the
per-bench continual-learning view from the eval fold.

BWT (backward transfer) and FWT (forward transfer) are NOT measurable on this
trajectory because the evaluation fold is fixed across cycles; that measurement
requires a different incremental-learning experimental design and is registered
as future work.
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BENCHES = ['fever', 'triviaqa', 'commonsense_qa', 'strategyqa', 'truthfulqa']
TRAINING = ['fever', 'triviaqa', 'commonsense_qa']
TRANSFER = ['strategyqa', 'truthfulqa']

BENCH_DISPLAY = {
    'fever': 'FEVER',
    'triviaqa': 'TriviaQA',
    'commonsense_qa': 'CommonsenseQA',
    'strategyqa': 'StrategyQA',
    'truthfulqa': 'TruthfulQA',
}

EVAL_DIR = ROOT / 'outputs/full_run/eval'
OUT_TEX = ROOT / 'thesis_report/figures/auto/tab_continual_retention.tex'


def em_of(samples, is_tqa=False):
    if not samples:
        return None
    if is_tqa:
        llm = [s['em_llm_judged'] for s in samples if s.get('em_llm_judged') is not None]
        if llm:
            return sum(llm) / len(llm)
    return sum(s.get('em', 0) for s in samples) / len(samples)


def load_eval_em(bench, cycle):
    p = EVAL_DIR / f'{bench}_cycle{cycle}.json'
    if not p.is_file():
        return None
    d = json.load(p.open())
    samples = d['samples'] if isinstance(d, dict) else d
    return em_of(samples, is_tqa=(bench == 'truthfulqa'))


print('Building tab_continual_retention.tex...')

ems = {b: [load_eval_em(b, c) for c in range(6)] for b in BENCHES}

lines = ['% Auto-generated by scripts/aggregate_section_5_5.py']
lines.append('% Per-bench eval-fold EM stability across the 6-cycle trajectory.')
lines.append('% BWT/FWT instruments NOT MEASURABLE on a fixed-eval-fold design;')
lines.append('% registered as future-work in chapter 6.')
lines.append('\\begin{table}[!htbp]')
lines.append('\\centering\\small')
lines.append('\\begin{tabular}{llrrrrrrr}')
lines.append('\\toprule')
lines.append('\\textbf{Panel} & \\textbf{Benchmark} & \\textbf{C0} & \\textbf{C5} & \\textbf{$\\Delta$ EM (pp)} & \\textbf{min} & \\textbf{max} & \\textbf{range} & \\textbf{Outcome} \\\\')
lines.append('\\midrule')


def render_row(panel, b):
    vals = ems[b]
    em_c0 = vals[0]
    em_c5 = vals[5]
    delta_pp = (em_c5 - em_c0) * 100 if em_c0 is not None and em_c5 is not None else float('nan')
    valid = [v for v in vals if v is not None]
    mn = min(valid)
    mx = max(valid)
    rng = (mx - mn) * 100
    # forgetting or stable
    if delta_pp < -2.0:
        out = 'forgetting'
    elif delta_pp > 2.0:
        out = 'forward gain'
    else:
        out = 'stable'
    return f'{panel} & {BENCH_DISPLAY[b]} & {em_c0:.3f} & {em_c5:.3f} & {delta_pp:+.2f} & {mn:.3f} & {mx:.3f} & {rng:.2f}pp & {out} \\\\'


for b in TRAINING:
    lines.append(render_row('train', b))
lines.append('\\midrule')
for b in TRANSFER:
    lines.append(render_row('transfer', b))
lines.append('\\bottomrule')
lines.append('\\end{tabular}')
lines.append('\\caption{Per-benchmark exact-match stability across the realised six-cycle trajectory on the evaluation fold. '
             'The columns report the exact match at the cycle-zero baseline and the cycle-five close, the cycle-zero-to-cycle-five change in percentage points, '
             'the per-benchmark minimum and maximum exact match across the six cycles and their range, and a qualitative outcome label (stable, forgetting, or forward gain) under a two-percentage-point threshold. '
             'The retention probe ratios reported in \\Cref{tab:pooled-trajectory} measure the retention-guard input on the registered multi-modal probe panel rather than the headline-benchmark axis; the present table reports the continual-learning view from the headline axis, so the two readings are complementary rather than redundant. '
             'Forward and backward transfer instruments in the formal sense of the continual-learning literature are not measurable on this trajectory because the evaluation fold is fixed across cycles; '
             'the matched-pair measurement that would supply those instruments requires the per-cycle data slice to vary across cycles and is registered as a future-work item in \\Cref{ch:conclusion}.}')
lines.append('\\label{tab:continual-retention}')
lines.append('\\end{table}')
OUT_TEX.write_text('\n'.join(lines) + '\n')
print(f'  wrote {OUT_TEX}')
