"""
scripts/aggregate_section_5_4.py
================================
Builds Ch5 §5.4 (Three-tier router efficiency) tables:
  - tab_tier_trajectory.tex   per-cycle pooled tier share + per-tier EM
  - tab_tier_latency.tex      per-cycle per-tier mean latency + pooled
  - tab_safety_override.tex   per-cycle safety-override firing count

Data sources:
  outputs/full_run/all_cycle_results.json   per-bench tier shares
  outputs/full_run/eval/<bench>_cycle<N>.json  per-sample tier + latency + escalated
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BENCHES = ['fever', 'triviaqa', 'commonsense_qa', 'strategyqa', 'truthfulqa']
EVAL_DIR = ROOT / 'outputs/full_run/eval'
OUT_DIR = ROOT / 'thesis_report/figures/auto'


def load_eval(bench: str, cycle: int):
    p = EVAL_DIR / f'{bench}_cycle{cycle}.json'
    if not p.is_file():
        return []
    d = json.load(p.open())
    return d['samples'] if isinstance(d, dict) else d


def per_cycle_aggregate():
    """Returns {cycle: {tier: {n, em_sum, lat_sum, chm_n}}}."""
    out = {}
    safety_count = {}
    for c in range(6):
        bucket = {1: {'n': 0, 'em_sum': 0.0, 'lat_sum': 0.0},
                  2: {'n': 0, 'em_sum': 0.0, 'lat_sum': 0.0},
                  3: {'n': 0, 'em_sum': 0.0, 'lat_sum': 0.0}}
        safety = 0
        total = 0
        for b in BENCHES:
            for s in load_eval(b, c):
                tier = s.get('tier')
                if tier in bucket:
                    is_tqa = (b == 'truthfulqa')
                    em = s['em_llm_judged'] if (is_tqa and s.get('em_llm_judged') is not None) else s.get('em', 0)
                    bucket[tier]['n'] += 1
                    bucket[tier]['em_sum'] += em
                    bucket[tier]['lat_sum'] += s.get('latency_ms', 0)
                if s.get('escalated'):
                    safety += 1
                total += 1
        out[c] = bucket
        safety_count[c] = (safety, total)
    return out, safety_count


def fmt_pct(x, dp=1):
    if x is None or x != x:
        return '--'
    return f'{x*100:.{dp}f}\\%'


def fmt(x, dp=3):
    if x is None or x != x:
        return '--'
    return f'{x:.{dp}f}'


# ============================================================================
# Build tables
# ============================================================================
agg, safety = per_cycle_aggregate()

# Table 1: tier_trajectory — pooled share + EM per tier per cycle
print('Building tab_tier_trajectory.tex...')
lines = ['% Auto-generated by scripts/aggregate_section_5_4.py']
lines.append('% Per-cycle pooled tier share + per-tier exact match.')
lines.append('\\begin{table}[!htbp]')
lines.append('\\centering\\small')
lines.append('\\begin{tabular}{c|cc|cc|cc|c}')
lines.append('\\toprule')
lines.append('  & \\multicolumn{2}{c|}{\\textbf{Tier 1 (memory)}} & \\multicolumn{2}{c|}{\\textbf{Tier 2 (zero-shot)}} & \\multicolumn{2}{c|}{\\textbf{Tier 3 (RAG)}} & \\\\')
lines.append('\\textbf{Cycle} & share & EM & share & EM & share & EM & \\textbf{Pooled EM} \\\\')
lines.append('\\midrule')

for c in range(6):
    counts = agg[c]
    total = sum(v['n'] for v in counts.values())
    row = [f'C{c}']
    pooled_em_num = 0.0
    pooled_em_den = 0
    for tier in [1, 2, 3]:
        v = counts[tier]
        share = v['n'] / total if total else 0
        em = v['em_sum'] / v['n'] if v['n'] else float('nan')
        row.append(fmt_pct(share, 1))
        row.append(fmt(em, 3))
        pooled_em_num += v['em_sum']
        pooled_em_den += v['n']
    pooled_em = pooled_em_num / pooled_em_den if pooled_em_den else float('nan')
    row.append(fmt(pooled_em, 3))
    lines.append(' & '.join(row) + ' \\\\')

lines.append('\\bottomrule')
lines.append('\\end{tabular}')
lines.append('\\caption{Per-cycle pooled tier share and per-tier exact match across the five-benchmark evaluation panel. '
             'For each cycle the table reports the share of evaluation queries served by each tier and the within-tier exact-match rate. '
             'The pooled exact match in the rightmost column is the sample-weighted mean over the three within-tier rates. '
             'The memory-direct tier (Tier 1) fires on a small share of evaluation queries because the evaluation fold is held content-hash disjoint from the training stream by construction; '
             'when Tier 1 does fire, every realised firing returns the correct stored answer (an exact-match rate of $1.0$), the empirical receipt for the Tier-1 floor corollary of \\Cref{cor:tier1-floor}. '
             'Tier 2 exact match at cycle zero exceeds Tier 3 exact match at cycle zero by approximately twelve percentage points, the self-improvement-as-distillation receipt: the parametric tier already outperforms the retrieval tier at cold-start because retrieval pulls evidence that is not always topical, and the self-improvement loop subsequently transfers retrieved knowledge into the parametric tier without re-routing.}')
lines.append('\\label{tab:tier-trajectory}')
lines.append('\\end{table}')
(OUT_DIR / 'tab_tier_trajectory.tex').write_text('\n'.join(lines) + '\n')
print(f'  wrote {OUT_DIR}/tab_tier_trajectory.tex')


# Table 2: tier_latency — per-cycle per-tier mean latency
print('Building tab_tier_latency.tex...')
lines = ['% Auto-generated by scripts/aggregate_section_5_4.py']
lines.append('% Per-cycle pooled latency from the production batched eval log.')
lines.append('% NOTE: per-tier latency cannot be honestly extracted from batched-eval logs')
lines.append('%       because latency_ms = batch_elapsed/N at bs=32, so per-tier amortised')
lines.append('%       readings reflect the per-batch mix not the intrinsic per-tier cost.')
lines.append('%       Only the pooled-per-cycle reading is deployment-relevant from this log.')
lines.append('\\begin{table}[!htbp]')
lines.append('\\centering\\small')
lines.append('\\begin{tabular}{cccc}')
lines.append('\\toprule')
lines.append('\\textbf{Cycle} & \\textbf{Pooled mean per-query (ms)} & \\textbf{Pooled per-query (s)} & \\textbf{Per-cycle wall time (s)} \\\\')
lines.append('\\midrule')

for c in range(6):
    counts = agg[c]
    total_lat_sum = sum(counts[t]['lat_sum'] for t in [1, 2, 3])
    total_lat_n = sum(counts[t]['n'] for t in [1, 2, 3])
    pooled_lat_ms = total_lat_sum / total_lat_n if total_lat_n else None
    per_query_s = pooled_lat_ms / 1000 if pooled_lat_ms else None
    cycle_wall_s = total_lat_sum / 1000 if pooled_lat_ms else None

    def lat_fmt(x, dp=0):
        return f'{x:.{dp}f}' if x is not None else '--'

    lines.append(f'C{c} & {lat_fmt(pooled_lat_ms, 0)} & {lat_fmt(per_query_s, 1)} & {lat_fmt(cycle_wall_s, 0)} \\\\')

lines.append('\\bottomrule')
lines.append('\\end{tabular}')
lines.append('\\caption{Per-cycle pooled wall-clock latency on the production batched evaluation log. '
             'Each cell reports the per-query mean over the full one thousand five hundred evaluation queries at the indicated cycle. '
             'Reported figures are the production-batched amortised values at the deployment batch size of thirty-two. '
             'Per-tier intrinsic latency is deliberately not decomposed from the production log because the per-sample latency record reflects the per-batch wall time divided by the batch size, '
             'so any per-tier amortisation reflects the per-batch tier mix rather than the per-tier compute cost. '
             'The intrinsic per-tier latency (memory lookup at unit batch, zero-shot generation at unit batch, retrieval-augmented generation at unit batch) is a separate measurement that the writeup-hardware envelope cannot host (the dense passage index does not fit in the available random-access memory), and the measurement is registered as a future-work item in \\Cref{ch:conclusion}.}')
lines.append('\\label{tab:tier-latency}')
lines.append('\\end{table}')
(OUT_DIR / 'tab_tier_latency.tex').write_text('\n'.join(lines) + '\n')
print(f'  wrote {OUT_DIR}/tab_tier_latency.tex')


# Table 3: safety override
print('Building tab_safety_override.tex...')
lines = ['% Auto-generated by scripts/aggregate_section_5_4.py']
lines.append('% Per-cycle safety override firing count on the eval fold.')
lines.append('\\begin{table}[!htbp]')
lines.append('\\centering\\small')
lines.append('\\begin{tabular}{ccccc}')
lines.append('\\toprule')
lines.append('\\textbf{Cycle} & \\textbf{Safety fires} & \\textbf{Total queries} & \\textbf{Fire rate} & \\textbf{Effect on EM} \\\\')
lines.append('\\midrule')
for c in range(6):
    fires, total = safety.get(c, (0, 0))
    rate = fires / total if total else 0
    lines.append(f'C{c} & {fires} & {total} & {rate*100:.2f}\\% & not measurable \\\\')
lines.append('\\bottomrule')
lines.append('\\end{tabular}')
lines.append('\\caption{Per-cycle safety override firing rate on the evaluation fold. '
             'The safety override forces the retrieval-augmented tier whenever the pre-routing confidence falls below the registered floor of $0.38$ (\\Cref{sec:router}). '
             'Across the realised trajectory, the safety override does not fire on any of the nine thousand evaluation queries observed across six cycles and five benchmarks. '
             'The empirical reading is that pre-routing confidence stays above the safety floor on the panel distribution, so the override is a contractual safety mechanism that never activates on the realised evaluation distribution rather than a frequent intervention. '
             'A trajectory on a more adversarial distribution, or with a higher safety floor, would exercise the override more visibly and is registered as a future-work item.}')
lines.append('\\label{tab:safety-override}')
lines.append('\\end{table}')
(OUT_DIR / 'tab_safety_override.tex').write_text('\n'.join(lines) + '\n')
print(f'  wrote {OUT_DIR}/tab_safety_override.tex')

print('\nAll 3 §5.4 tables built.')
