"""
scripts/aggregate_section_5_6.py
================================
Builds the §5.6 theorem-check receipt tables that don't already exist:
  - tab_self_correction_check.tex   per-cycle retroactive prune rate trajectory (cor:self-correction receipt)
  - tab_theorem_receipts_summary.tex  one row per theorem/corollary with verdict + receipt anchor

Existing tables reused from prior aggregators:
  - tab_pi_store_trajectory.tex      (§5.6.1 thm:purity receipt)
  - tab_stochastic_equilibrium.tex   (§5.6.3 cor:stochastic-equilibrium receipt)
  - tab_tier_chm_trajectory.tex      (§5.6.4 cor:tier1-floor receipt)
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / 'thesis_report/figures/auto'

# Self-correction prune rate trajectory
print('Building tab_self_correction_check.tex...')
cycle_data = []
for c in [1, 2, 3, 5]:
    p = ROOT / f'outputs/full_run/retroverify_cycle{c}.json'
    d = json.load(p.open())
    rv = d['retroverify']
    total = rv.get('total', 0)
    pruned = rv.get('pruned', 0)
    updated = rv.get('updated', 0)
    rate = (pruned / total * 100) if total else 0
    cycle_data.append({'cycle': c, 'total': total, 'pruned': pruned, 'updated': updated, 'rate': rate})

lines = ['% Auto-generated by scripts/aggregate_section_5_6.py']
lines.append('% Per-cycle retroactive prune rate (cor:self-correction empirical receipt)')
lines.append('\\begin{table}[!htbp]')
lines.append('\\centering\\small')
lines.append('\\begin{tabular}{cccccc}')
lines.append('\\toprule')
lines.append('\\textbf{Cycle} & \\textbf{Pool size at pass} & \\textbf{Updated} & \\textbf{Pruned} & \\textbf{Prune rate} & \\textbf{Survivor share} \\\\')
lines.append('\\midrule')

for row in cycle_data:
    survivor_share = (row['updated'] / row['total'] * 100) if row['total'] else 0
    lines.append(f'C{row["cycle"]} & {row["total"]:,} & {row["updated"]:,} & {row["pruned"]:,} & '
                 f'{row["rate"]:.1f}\\% & {survivor_share:.1f}\\% \\\\')

# Note about cycle 4
lines.append('\\midrule')
lines.append('\\multicolumn{6}{l}{\\textit{Cycle 4: retroactive pass skipped under the cycle-four retention abort (skip-retroverify-on-abort patch).}} \\\\')
lines.append('\\bottomrule')
lines.append('\\end{tabular}')
lines.append('\\caption{Per-cycle retroactive prune-rate trajectory on the committed-cycle subsequence. '
             'Each row reports the storage-pool size at the cycle-boundary retroactive pass, the number of entries whose composite was refreshed (updated), the number of entries removed under the registered prune threshold $\\tau_{\\text{retro}} = 0.50$, the prune rate as a share of the pool, and the survivor share as the complement. '
             'The prune-rate trajectory $13.0 \\rightarrow 9.2 \\rightarrow 6.6 \\rightarrow 3.7$ percent across the four committed cycles is the empirical receipt for \\Cref{cor:self-correction}: an improving verifier removes low-quality entries at a decreasing rate as the pool composition shifts toward higher-confidence survivors. '
             'Cycle four\'s retroactive pass was skipped under the asymmetric-rollback contract (the post-fine-tune verifier is the rolled-back cycle-three verifier, so re-scoring the pool would not produce new information).}')
lines.append('\\label{tab:self-correction-check}')
lines.append('\\end{table}')

(OUT_DIR / 'tab_self_correction_check.tex').write_text('\n'.join(lines) + '\n')
print(f'  wrote {OUT_DIR}/tab_self_correction_check.tex')


# Theorem-receipts summary table
print('Building tab_theorem_receipts_summary.tex...')

receipts = [
    ('T1', 'thm:purity', 'Theorem', 'PASS',
     'Pooled $\\pi_t \\in [0.7226, 0.7536]$; per-bench min $0.6637$; all readings clear $0.64$ floor by $8$ to $11$ percentage points.',
     'tab:pi-store-trajectory'),
    ('T2', 'thm:bayes-purity', 'Remark', 'identity',
     'Mathematical scaffolding (Bayes\'-rule identity); no within-horizon empirical receipt.',
     '--'),
    ('T3', 'thm:monotone', 'Theorem', 'PARTIAL',
     'Sign alignment holds on three of four cal-fold transitions; honest reverse-sign disclosure at $C3 \\to C5$.',
     'tab:pi-store-trajectory'),
    ('T4', 'thm:monotone-purification', 'Remark', 'identity',
     'Mathematical scaffolding (derivative of T2); no within-horizon empirical receipt.',
     '--'),
    ('T5', 'thm:convergence', 'Theorem', 'BOUNDED-BAND',
     'Pooled $\\pi_t$ confined to a band of width $\\le 0.031$ across the six-cycle horizon; geometric-rate test deferred to a $\\ge 15$-committed-cycle horizon.',
     'tab:pi-store-trajectory'),
    ('T6', 'thm:bayes-convergence', 'Remark', 'identity',
     'Mathematical scaffolding (monotone-map fixed-point theorem); no within-horizon empirical receipt.',
     '--'),
    ('T7', 'thm:asymptotic-elim', 'Remark', 'identity',
     'Mathematical scaffolding (law of total probability); no within-horizon empirical receipt.',
     '--'),
    ('C1', 'cor:tier1-floor', 'Corollary', 'CAPABILITY',
     'CHM$_1 = 0$ on each of the seven realised Tier-1 firings; pool-side ceiling $1 - \\pi_{\\text{store}} \\approx 0.36$ holds with substantial slack.',
     'tab:tier-chm-trajectory'),
    ('C2', 'cor:convergence-rate', 'Corollary', 'PROJECTED',
     'Half-life measurement deferred to $\\ge 15$-committed-cycle horizon; qualitatively consistent with shrinking per-cycle composite decrement.',
     '--'),
    ('C3', 'cor:corpus-floor', 'Remark', 'deferred',
     'Per-sample top-$k$ passage IDs not persisted; proxy receipt deferred to future-work re-retrieval pass.',
     '--'),
    ('C4', 'cor:self-correction', 'Corollary', 'PARTIAL',
     'Prune-rate decline $13 \\to 9 \\to 7 \\to 4$ percent across committed cycles supports directional claim; survivor-side histogram deferred.',
     'tab:self-correction-check'),
    ('C5', 'cor:stochastic-equilibrium', 'Corollary', 'PASS',
     '$\\pi_{\\mathrm{commit}} = 4/5 = 0.80$ strictly in $(0,1)$; memory grows monotonically across the C4 abort; clean empirical receipt.',
     'tab:stochastic-equilibrium'),
]

lines = ['% Auto-generated by scripts/aggregate_section_5_6.py']
lines.append('% Theorem-receipts summary table — one row per formal claim with verdict + receipt anchor.')
lines.append('\\begin{table}[!htbp]')
lines.append('\\centering\\footnotesize')
lines.append('\\begin{tabular}{p{0.4cm}p{2.6cm}p{1.5cm}p{1.5cm}p{6cm}p{2.5cm}}')
lines.append('\\toprule')
lines.append('\\textbf{ID} & \\textbf{Label} & \\textbf{Type} & \\textbf{Verdict} & \\textbf{Receipt summary} & \\textbf{Anchor} \\\\')
lines.append('\\midrule')
for rid, lbl, typ, verdict, receipt, anchor in receipts:
    safe_lbl = lbl.replace('_', r'\_')
    safe_anchor = f'\\Cref{{{anchor}}}' if anchor != '--' else '--'
    lines.append(f'{rid} & \\texttt{{{safe_lbl}}} & {typ} & {verdict} & {receipt} & {safe_anchor} \\\\')
lines.append('\\bottomrule')
lines.append('\\end{tabular}')
lines.append('\\caption{Theorem and corollary receipts summary against the realised six-cycle trajectory. '
             'Each row pairs one formal claim from \\Cref{sec:theory} with a verdict and the table anchor where its empirical receipt is reported. '
             'PASS verdicts are claims whose receipt is satisfied directly by the realised trajectory. '
             'PARTIAL verdicts are claims whose directional prediction is supported by the realised data but whose sharper form requires either a longer horizon or an instrument not present in the artefact set. '
             'BOUNDED-BAND, PROJECTED, and CAPABILITY verdicts label claims that the chapter-four restructuring carries with explicit scope qualifiers as discussed in \\Cref{sec:theory}. '
             'Mathematical scaffolding identities (Remarks) do not carry an empirical receipt by design and are listed for completeness.}')
lines.append('\\label{tab:theorem-receipts-summary}')
lines.append('\\end{table}')
(OUT_DIR / 'tab_theorem_receipts_summary.tex').write_text('\n'.join(lines) + '\n')
print(f'  wrote {OUT_DIR}/tab_theorem_receipts_summary.tex')

print('\nAll §5.6 tables built.')
