"""
scripts/aggregate_section_5_3.py
================================
Builds tab_decision_distribution.tex for Ch5 §5.3 (Four-outcome decision distribution).

Reads per-bench calibration-fold JSONs in outputs/full_run/cycle_N/calibration/
across the training panel and computes per-decision counts + per-decision EM.

C0 (cold-start, no calibration fold) and C4 (aborted, no calibration fold logged)
are excluded by design; the trajectory therefore reports the four committed cycles
where the storage-gate four-outcome breakdown is empirically observable.
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TRAINING = ['fever', 'triviaqa', 'commonsense_qa']
COMMIT_CYCLES = [1, 2, 3, 5]
DECISIONS = ['STORE', 'DEFERRED', 'DISCARD', 'ABSTAIN']

DEC_DISPLAY = {
    'STORE':    'Store',
    'DEFERRED': 'Defer',
    'DISCARD':  'Discard',
    'ABSTAIN':  'Abstain',
}

OUT_TEX = ROOT / 'thesis_report/figures/auto/tab_decision_distribution.tex'


def compute() -> dict:
    out = {}
    for c in COMMIT_CYCLES:
        bucket = defaultdict(lambda: {'n': 0, 'em_sum': 0.0})
        for b in TRAINING:
            p = ROOT / f'outputs/full_run/cycle_{c}/calibration/{b}_cycle{c}.json'
            if not p.is_file():
                continue
            d = json.load(p.open())
            samples = d['samples'] if isinstance(d, dict) else d
            for s in samples:
                dec = s.get('decision') or ('ABSTAIN' if s.get('abstained') else 'UNKNOWN')
                if dec == 'UNKNOWN':
                    continue
                bucket[dec]['n'] += 1
                bucket[dec]['em_sum'] += s.get('em', 0)
        total = sum(v['n'] for v in bucket.values())
        out[c] = {
            dec: {
                'n': v['n'],
                'share': v['n'] / total if total else 0,
                'em': (v['em_sum'] / v['n']) if v['n'] else 0,
            }
            for dec, v in bucket.items()
        }
    return out


def render(results: dict) -> str:
    lines = ['% Auto-generated by scripts/aggregate_section_5_3.py']
    lines.append('% Per-cycle four-outcome decision distribution on the training-panel calibration fold.')
    lines.append('% Cycles 1,2,3,5 only (C0 is cold-start before first calibration; C4 was aborted under retention guard).')
    lines.append('\\begin{table}[!htbp]')
    lines.append('\\centering\\small')
    lines.append('\\begin{tabular}{ccccccccc}')
    lines.append('\\toprule')
    lines.append(' & \\multicolumn{2}{c}{\\textbf{Store}} & \\multicolumn{2}{c}{\\textbf{Defer}} & \\multicolumn{2}{c}{\\textbf{Discard}} & \\multicolumn{2}{c}{\\textbf{Abstain}} \\\\')
    lines.append('\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}\\cmidrule(lr){8-9}')
    lines.append('\\textbf{Cycle} & share & EM & share & EM & share & EM & share & EM \\\\')
    lines.append('\\midrule')

    for c in COMMIT_CYCLES:
        r = results[c]
        row = [f'C{c}']
        for dec in DECISIONS:
            v = r.get(dec, {'share': 0, 'em': 0})
            row.append(f"{v['share']*100:.1f}\\%")
            row.append(f"{v['em']:.2f}")
        lines.append(' & '.join(row) + ' \\\\')

    lines.append('\\bottomrule')
    lines.append('\\end{tabular}')
    lines.append('\\caption{Per-cycle four-outcome decision distribution on the training-panel calibration fold and the per-outcome exact-match rate. '
                 'Each cycle reports the share of the calibration-fold sample that falls into each of the four registered outcomes (store, defer, discard, abstain) under the locked storage-gate cut-points, alongside the exact-match rate within each outcome class. '
                 'The sorting order $\\mathrm{EM}(\\text{store}) > \\mathrm{EM}(\\text{defer}) > \\mathrm{EM}(\\text{discard}) > \\mathrm{EM}(\\text{abstain})$ is preserved at every reported cycle, the structural receipt that the fixed-threshold gate continues to sort the candidate pool by correctness as the underlying signal distribution drifts across cycles. '
                 'Cycle zero (cold-start state before the first calibration refit) and cycle four (aborted under the retention guard, with no calibration fold persisted) are absent from the trajectory by design.}')
    lines.append('\\label{tab:decision-distribution}')
    lines.append('\\end{table}')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    results = compute()
    OUT_TEX.write_text(render(results))
    print(f'wrote {OUT_TEX}')
